import assert from 'node:assert/strict';
import { test } from 'node:test';
import { canPrepareUpdate, updateBlockers, UpdateMaintenance, type UpdateReadiness } from '../server/update-maintenance.ts';
import { shouldPromptForUpdate, updateDownloadPercent, updateIsBusy, updateIsInstalling, type DesktopUpdateSnapshot } from '../shared/desktop-update.ts';
import { DatabaseSync } from 'node:sqlite';
import { assertReadableWorkspaceDatabase } from '../server/data-format.ts';
import { readFileSync } from 'node:fs';
import { stripTypeScriptTypes } from 'node:module';

test('renderer native calls have generated permissions and access from the owned desktop window', () => {
  const read = (file: string) => readFileSync(new URL('../' + file, import.meta.url), 'utf8');
  const configuration = JSON.parse(read('src-tauri/tauri.conf.json'));
  const capability = configuration.app.security.capabilities.find((entry: { identifier: string }) => entry.identifier === 'desktop-main');
  assert.deepEqual(capability.windows, ['main']);
  assert.equal(capability.local, false);
  assert.deepEqual(capability.remote.urls, ['http://127.0.0.1:*']);
  const manifest = read('src-tauri/build.rs').match(/\.commands\(&\[([\s\S]*?)\]\)/)?.[1];
  assert(manifest);
  const generatedCommands = new Set([...manifest.matchAll(/"([a-z_]+)"/g)].map(match => match[1]));
  const handler = read('src-tauri/src/main.rs').match(/tauri::generate_handler!\[([\s\S]*?)\]/)?.[1];
  assert(handler);
  const handled = new Set(handler.split(',').map(value => value.trim().split('::').at(-1)));
  const calls = new Set<string>();
  for (const file of ['src/desktop.ts', 'src/i18n.ts']) {
    const source = stripTypeScriptTypes(read(file), { mode: 'strip', sourceUrl: file });
    const commands = [...source.matchAll(/\binvoke\s*\(\s*['"]([a-z_]+)['"]/g)];
    assert.equal(commands.length, [...source.matchAll(/\binvoke\s*\(/g)].length, 'Native bridge calls must use fixed command names');
    for (const match of commands) calls.add(match[1]);
  }
  assert(calls.size > 0);
  for (const command of calls) {
    assert(handled.has(command), `${command}: missing native handler`);
    assert(generatedCommands.has(command), `${command}: missing Tauri permission generation`);
    const permission = 'allow-' + command.replaceAll('_', '-');
    assert(capability.permissions.includes(permission), `${command}: denied to the desktop workspace`);
    const declaration = read(`src-tauri/permissions/autogenerated/${command}.toml`);
    assert(declaration.includes(`identifier = "${permission}"`), `${command}: missing generated permission`);
    assert(declaration.includes(`commands.allow = ["${command}"]`), `${command}: permission does not enable the native command`);
  }
});

const idle = (): UpdateReadiness => ({ tasks: [], queues: [], workflows: [], remoteTasks: [], brainTasks: [], transfers: 0, operations: 0, modelChecks: 0 });

test('an incompatible future database is rejected before its format marker or content changes', () => {
  const database = new DatabaseSync(':memory:');
  try {
    database.exec("CREATE TABLE future_state(value TEXT); INSERT INTO future_state VALUES ('keep'); PRAGMA user_version=5;");
    assert.throws(() => assertReadableWorkspaceDatabase(database), /更高版本/);
    assert.equal(database.prepare('PRAGMA user_version').get()?.user_version, 5);
    assert.equal(database.prepare('SELECT value FROM future_state').get()?.value, 'keep');
    database.exec('PRAGMA user_version=3');
    assert.equal(assertReadableWorkspaceDatabase(database), 3);
  } finally { database.close(); }
});

test('updates preserve active, waiting, uncertain and independent collaborative work', () => {
  for (const state of ['running', 'waiting_approval', 'waiting_input', 'stopping', 'interrupted', 'review'] as const)
    assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), tasks: [{ state }] })), false, state);
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), tasks: [{ state: 'accepted' }, { state: 'failed' }, { state: 'stopped' }, { state: 'open' }] })), true);
  for (const state of ['waiting', 'held', 'admitted'] as const)
    assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), queues: [{ state }] })), false, state);
  for (const state of ['planning', 'running', 'paused', 'stopping'] as const)
    assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), workflows: [{ state }] })), false, state);
  for (const field of ['transfers', 'operations', 'modelChecks'] as const)
    assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), [field]: 1 })), false, field);
});

test('updates wait for remote controls, delivery acknowledgements and Brain results', () => {
  const done = { status: 'accepted' as const, executionState: 'accepted' as const, controlPending: false, deliveryPending: false };
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), remoteTasks: [done] })), true);
  for (const delta of [{ controlPending: true }, { deliveryPending: true }, { executionState: 'interrupted' as const }, { status: 'pending' as const }])
    assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), remoteTasks: [{ ...done, ...delta }] })), false);
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), brainTasks: [{ status: 'completed', deliveryPending: true }] })), false);
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), brainTasks: [{ status: 'queued', deliveryPending: false }] })), false);
});

test('updates wait between queued conversation rounds and allow a deliberately paused message queue', () => {
  const workflow = { state: 'completed' as const, messages: [{ requestID: 'next', text: 'Continue', state: 'queued' as const, inputFiles: [], createdAt: '' }] };
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), workflows: [workflow] })), false);
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), workflows: [{ ...workflow, queuePaused: true }] })), true);
  assert.equal(canPrepareUpdate(updateBlockers({ ...idle(), workflows: [{ ...workflow, roundRequestID: 'next' }] })), true);
});

test('maintenance atomically fences intake, tracks in-flight writes and recovers from a lost caller', () => {
  let clock = 1000;
  const gate = new UpdateMaintenance(() => clock);
  const finish = gate.enterOperation()!;
  assert.equal(gate.pending, 1);
  assert.equal(gate.acquire(), true);
  assert.equal(gate.acquire(), false);
  assert.equal(gate.enterOperation(), null);
  finish(); finish();
  assert.equal(gate.pending, 0);
  gate.release();
  const second = gate.enterOperation()!; second();
  assert.equal(gate.acquire(), true);
  clock += 120_001;
  assert.equal(gate.active, false);
  assert.equal(gate.acquire(), true);
  assert.equal(gate.commit(), true);
  assert.equal(gate.commit(), false);
  gate.release(); clock += 120_001;
  assert.equal(gate.active, true, 'A committed shutdown cannot be cancelled or expire');
  assert.equal(gate.enterOperation(), null);
});

const snapshot = (): DesktopUpdateSnapshot => ({ phase: 'available', currentVersion: '0.1.4', release: { version: '0.1.5', notes: '', publishedAt: null },
  skippedVersion: null, lastCheckedAt: null, downloadedBytes: 0, totalBytes: null, error: null, blockers: null, revision: 1 });

test('only the selected skipped version is quiet and progress cannot exceed its bounds', () => {
  const value = snapshot();
  assert.equal(shouldPromptForUpdate(value), true);
  value.skippedVersion = '0.1.5';
  assert.equal(shouldPromptForUpdate(value), false);
  value.release!.version = '0.1.6';
  assert.equal(shouldPromptForUpdate(value), true);
  value.phase = 'downloading';
  assert.equal(shouldPromptForUpdate(value), false);
  assert.equal(updateDownloadPercent(value), null);
  value.totalBytes = 100; value.downloadedBytes = 60;
  assert.equal(updateDownloadPercent(value), 60);
  value.downloadedBytes = 150;
  assert.equal(updateDownloadPercent(value), 100);
  assert.equal(updateIsBusy('ready'), false);
  assert.equal(updateIsBusy('preparing'), true);
});

test('every native installation phase stays busy without displaying an update offer', () => {
  for (const phase of ['preparing', 'stopping', 'backing_up', 'installing'] as const) {
    assert.equal(updateIsInstalling(phase), true, phase);
    assert.equal(updateIsBusy(phase), true, phase);
    assert.equal(shouldPromptForUpdate({ ...snapshot(), phase }), false, phase);
  }
  for (const phase of ['ready', 'available', 'error', 'downloading'] as const)
    assert.equal(updateIsInstalling(phase), false, phase);
});
