// Read-only consumer of existing candidate/public bytes. No build or publication.
import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,readdir,copyFile,lstat,unlink} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {join,resolve,dirname} from 'node:path';
import {pathToFileURL} from 'node:url';
const base=import.meta.dirname,sha=b=>createHash('sha256').update(b).digest('hex'),json=async p=>JSON.parse((await readFile(p,'utf8')).replace(/^\uFEFF/,''));
const fixed=await json(join(base,'fixed-inputs.json')),frozen=await json(join(base,'frozen-methods.json')),[platform,requestedProduct]=process.argv.slice(2),product=resolve(requestedProduct||'');
const git=(...args)=>execFileSync('git',args,{cwd:product,windowsHide:true,maxBuffer:128*1024**2,stdio:['ignore','pipe','pipe']});
const output=join(resolve(process.env.GITHUB_WORKSPACE),'test-results/readonly-consumer',platform),work=join(product,'.data/verification/independent-readonly-0130');await mkdir(output,{recursive:true});await mkdir(work,{recursive:true});
const report={schemaVersion:1,status:'running',at:new Date().toISOString(),platform,version:fixed.version,productCommit:fixed.productCommit,productTree:fixed.productTree,consumerCommit:process.env.GITHUB_SHA,workflowRunID:process.env.GITHUB_RUN_ID,workflowAttempt:process.env.GITHUB_RUN_ATTEMPT,controllerSHA256:sha(await readFile(new URL(import.meta.url))),fixedInputsSHA256:sha(await readFile(join(base,'fixed-inputs.json'))),frozenMethodsSHA256:sha(await readFile(join(base,'frozen-methods.json'))),producerBuildExecuted:false,publicationExecuted:false,storageMutations:0,methods:[]};let stage='frozen-methods';
let verifiedReaderNode=process.execPath;
function run(file,args=[]){execFileSync(verifiedReaderNode,[file,...args],{cwd:product,windowsHide:true,timeout:2_400_000,maxBuffer:32*1024**2,stdio:['ignore','pipe','pipe'],env:{...process.env}});console.log('Independent consumer completed '+stage);}
const api=p=>JSON.parse(execFileSync('gh',['api','--method','GET','repos/rivloom/rivloom-desktop/'+p],{encoding:'utf8',windowsHide:true,timeout:60000,maxBuffer:8*1024**2,stdio:['ignore','pipe','pipe']}));
function safeReason(value){
 return String(value).split(/[\r\n]/)[0].replace(/https?:\/\/[^\s"'<>]+/g,raw=>{try{const u=new URL(raw);u.search='';u.hash='';u.username='';u.password='';return ['downloads.rivloom.com','rivloom.com','api.github.com','nodejs.org','www.7-zip.org'].includes(u.hostname)?u.origin+u.pathname:'[external URL]';}catch{return '[URL]';}}).replace(/(?:Bearer\s+\S+|gh[pousr]_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+)/gi,'[redacted]').replace(/(?:token|password|authorization|secret|sig|signature)\s*[=:]\s*[^\s,;]+/gi,'[redacted]').slice(0,320);
}
function diagnostics(error){
 const childText=String(error.stderr||'').slice(-16384),codes=['ERR_TLS_CERT_ALTNAME_INVALID','CERT_HAS_EXPIRED','UNABLE_TO_VERIFY_LEAF_SIGNATURE','ECONNRESET','ECONNREFUSED','ETIMEDOUT','UND_ERR_CONNECT_TIMEOUT','UND_ERR_HEADERS_TIMEOUT','UND_ERR_SOCKET','EACCES','ENOENT','unexpected_redirect','tool_redirect_limit'];
 const hints=codes.filter(code=>childText.includes(code)||error.code===code||error.cause?.code===code),pattern=childText+' '+String(error.message||'');const result={errorType:['AssertionError','Error','TypeError'].includes(error.name)?error.name:'Error',childExitCode:Number.isSafeInteger(error.status)?error.status:null,transportClass:hints.includes('unexpected_redirect')||hints.includes('tool_redirect_limit')?'unexpected_redirect':hints.some(c=>/TLS|CERT|VERIFY_LEAF/.test(c))||/\b(?:tls|ssl|x509|certificate)\b/i.test(pattern)?'tls':hints.some(c=>/TIMEOUT/.test(c))||/timed? ?out|timeout/i.test(pattern)?'timeout':hints.some(c=>/ECONN/.test(c))||/connection (?:reset|refused)/i.test(pattern)?'connection':hints.includes('EACCES')?'permission':hints.includes('ENOENT')?'missing-file-or-tool':'not-classified',safeCodes:hints};
 const reason=error.code==='ERR_ASSERTION'?error.message:childText.match(/AssertionError(?:\s*\[[^\]]*\])?:\s*([^\r\n]*)/)?.[1];if(reason)result.assertionReason=safeReason(reason);
 if(error.code==='ERR_ASSERTION')for(const name of ['actual','expected'])if(typeof error[name]==='number'||typeof error[name]==='boolean'||typeof error[name]==='string'&&/^[a-f0-9]{40}(?:[a-f0-9]{24})?$/.test(error[name]))result[name]=error[name];return result;
}
async function get(url,limit){const r=await fetch(url,{redirect:'error',headers:{'accept-encoding':'identity','cache-control':'no-cache'},signal:AbortSignal.timeout(240000)});assert.equal(r.status,200);const parts=[];let n=0;for await(const b of r.body){n+=b.length;assert(n<=limit);parts.push(Buffer.from(b));}return Buffer.concat(parts);}
async function getWindowsExtractor(tool){
 assert.equal(tool.version,'22.01');assert.equal(tool.fileName,'7z2201-x64.exe');assert.equal(tool.maximumBytes,8*1024**2);assert.equal(tool.maximumRedirects,4);assert.match(tool.installerSHA256,/^[a-f0-9]{64}$/);
 const accepted=u=>u.protocol==='https:'&&!u.username&&!u.password&&(!u.port||u.port==='443')&&(u.hostname==='sourceforge.net'||u.hostname==='downloads.sourceforge.net'||/^[a-z0-9-]+\.dl\.sourceforge\.net$/.test(u.hostname));
 const fail=code=>Object.assign(new Error('Fixed Windows extractor request rejected'),{code});
 let url;try{url=new URL(tool.url)}catch{throw fail('unexpected_redirect')}
 if(!accepted(url))throw fail('unexpected_redirect');
 const signal=AbortSignal.timeout(240000);let redirects=0;
 for(;;){
  const response=await fetch(url,{redirect:'manual',headers:{'accept-encoding':'identity','cache-control':'no-cache'},signal});
  if([301,302,303,307,308].includes(response.status)){
   const location=response.headers.get('location');await response.body?.cancel();
   if(redirects++>=tool.maximumRedirects)throw fail('tool_redirect_limit');
   if(!location)throw fail('unexpected_redirect');
   try{url=new URL(location,url)}catch{throw fail('unexpected_redirect')}
   if(!accepted(url))throw fail('unexpected_redirect');
   continue;
  }
  if(response.status!==200){await response.body?.cancel();assert.equal(response.status,200,'Fixed extractor HTTP status');}
  const parts=[];let bytes=0;
  for await(const part of response.body){bytes+=part.length;assert(bytes<=tool.maximumBytes,'Fixed extractor exceeds 8 MiB');parts.push(Buffer.from(part));}
  const archive=Buffer.concat(parts);assert.equal(sha(archive),tool.installerSHA256,'Fixed 7-Zip installer SHA256 differs');return archive;
 }
}
try{
 stage='hosted-and-product-source-identity';assert(['windows','linux'].includes(platform));assert.equal(process.version,'v24.19.0');assert.equal(process.platform,platform==='windows'?'win32':'linux');assert.equal(process.arch,'x64');
 assert.equal(process.env.GITHUB_ACTIONS,'true');assert.equal(process.env.RUNNER_ENVIRONMENT,'github-hosted');assert.equal(process.env.GITHUB_REPOSITORY,'rivloom/rivloom-desktop');assert.equal(process.env.GITHUB_EVENT_NAME,'workflow_dispatch');assert.equal(process.env.GITHUB_REF,'refs/heads/codex/release-readonly-0130-20261008');assert.match(process.env.EXPECTED_CONSUMER_COMMIT||'',/^[a-f0-9]{40}$/);assert.equal(process.env.GITHUB_SHA,process.env.EXPECTED_CONSUMER_COMMIT);
 assert.equal(git('rev-parse','HEAD').toString().trim(),fixed.productCommit);assert.equal(git('rev-parse','HEAD^{tree}').toString().trim(),fixed.productTree);assert.equal(git('status','--porcelain').toString().trim(),'');assert.equal(execFileSync('git',['rev-parse','HEAD'],{cwd:resolve(base,'../..'),encoding:'utf8',windowsHide:true}).trim(),process.env.EXPECTED_CONSUMER_COMMIT);
 stage='frozen-methods';
 for(const row of frozen.files){assert.equal(sha(await readFile(join(base,row.path))),row.sha256);report.methods.push({path:row.path,beforeSHA256:row.beforeSHA256,sha256:row.sha256,environmentAdaptations:row.adaptations});}assert.equal(frozen.productCommit,fixed.productCommit);assert.equal(frozen.productTree,fixed.productTree);
 for(const row of fixed.criticalFiles)assert.equal(sha(Buffer.from(git('show',fixed.productCommit+':'+row.path).toString('utf8').replaceAll('\r\n','\n'))),row.canonicalSHA256);
 stage='live-same-source-ci';report.sameSourceGates=[];
 for(const [name,path,count] of [['windowsCI','ci.yml',3],['windowsServices','windows-services.yml',21],['lan','lan-regression.yml',2],['linux','linux-ci.yml',1]]){const r=api('actions/runs/'+fixed.runs[name]);assert.equal(r.head_sha,fixed.productCommit);assert.equal(r.head_branch,'main');assert.equal(r.path,'.github/workflows/'+path);assert.equal(r.event,'push');assert.equal(r.status,'completed');assert.equal(r.conclusion,'success');const jobs=api(`actions/runs/${r.id}/attempts/${r.run_attempt}/jobs?per_page=100`);assert.equal(jobs.total_count,count);assert.equal(jobs.jobs.length,count);assert(jobs.jobs.every(j=>j.status==='completed'&&j.conclusion==='success'&&j.head_sha===fixed.productCommit));report.sameSourceGates.push({name,id:r.id,attempt:r.run_attempt,headSHA:r.head_sha,jobs:jobs.jobs.map(j=>({id:j.id,name:j.name,conclusion:j.conclusion}))});}
 for(const target of ['windows','linux']){await mkdir(join(work,target));for(const row of frozen.files.filter(r=>r.path.startsWith(target+'/')))await copyFile(join(base,row.path),join(work,row.path));}
 await writeFile(join(work,'acceptance-review-inputs.json'),JSON.stringify({criticalFiles:fixed.criticalFiles})+'\n');
 const source={version:fixed.version,commit:fixed.productCommit,tree:fixed.productTree,runtimeCore:fixed.runtimeCore,runs:fixed.runs,linuxArtifactID:fixed.linuxArtifactID,gates:'passed'};await writeFile(join(work,'release-source.json'),JSON.stringify(source)+'\n');
 if(platform==='windows'){
  stage='actual-fixed-reader-node';const setupNodeSHA256=sha(await readFile(process.execPath));assert.equal(setupNodeSHA256,fixed.windowsInputs.nodeSHA256,'Hosted reader Node binary differs from the original official pinned Windows binary');report.readerNode={version:process.version,setupNodeSHA256,officialPinnedBinarySHA256:fixed.windowsInputs.nodeSHA256,byteMatch:true};
  stage='original-pinned-extractor';const tools=join(work,'tools'),unpacked=join(tools,'7zip2201');await mkdir(tools);const archive=join(tools,fixed.windowsExtractorBootstrap.fileName);await writeFile(archive,await getWindowsExtractor(fixed.windowsExtractorBootstrap),{flag:'wx'});report.extractorBootstrap={version:fixed.windowsExtractorBootstrap.version,installerSHA256:sha(await readFile(archive)),maximumRedirects:fixed.windowsExtractorBootstrap.maximumRedirects,authorizationSent:false};
  execFileSync('C:/Program Files/7-Zip/7z.exe',['x','-y','-bsp0','-o'+unpacked,archive],{windowsHide:true,timeout:60000,maxBuffer:2*1024**2,stdio:['ignore','pipe','pipe']});
  const matches=[];async function find(p){for(const e of await readdir(p,{withFileTypes:true})){assert(!e.isSymbolicLink());const f=join(p,e.name);if(e.isDirectory())await find(f);else if(e.name.toLowerCase()==='7z.exe'&&sha(await readFile(f))===fixed.extractorSHA256)matches.push(f);}}await find(unpacked);assert.equal(matches.length,1);
  const win=join(work,'windows'),inputs={...fixed.windowsInputs,extractor:{path:matches[0],sha256:fixed.extractorSHA256}};await writeFile(join(win,'verification-inputs.json'),JSON.stringify(inputs,null,2)+'\n');await mkdir(join(win,'trust'));await writeFile(join(win,'trust/updater.pub'),git('show',fixed.productCommit+':src-tauri/updater.pub'));await writeFile(join(win,'prepared-bundle.json'),JSON.stringify({files:frozen.files.filter(r=>r.path.startsWith('windows/')).map(r=>({path:r.path.slice(8),sha256:r.sha256}))})+'\n');
  stage='source-binding';run(join(win,'bind-release-source.mjs'),[fixed.productCommit,product]);stage='candidate-binding';run(join(win,'bind-candidate.mjs'),[String(fixed.runs.windowsRelease),String(fixed.windowsArtifactID)]);stage='actual-reader-preflight';run(join(win,'preflight-windows-candidate.mjs'));stage='candidate-eight-proofs-static-and-fulltree';run(join(win,'verify-candidate.mjs'),[String(fixed.runs.windowsRelease),String(fixed.windowsArtifactID)]);
  const candidateRoot=join(win,`candidate-${fixed.runs.windowsRelease}-${fixed.windowsArtifactID}`),retrieval=await json(join(candidateRoot,'retrieval.json')),candidate=await json(join(candidateRoot,'candidate-verification.json'));
  assert.deepEqual({bytes:retrieval.artifact.bytes,sha256:retrieval.artifact.sha256},fixed.expectedWindowsArchive,'Candidate archive differs from the reviewed frozen artifact');assert.deepEqual({bytes:candidate.installer.bytes,sha256:candidate.installer.sha256},fixed.expectedWindowsInstaller,'Candidate installer differs from the reviewed public package');
  stage='public-full-get-and-original-key-package-signature';run(join(win,'verify-release.mjs'),['windows']);const publicProof=await json(join(win,'windows-public-verification.json'));assert.deepEqual({bytes:publicProof.bytes,sha256:publicProof.sha256},fixed.expectedWindowsInstaller,'Public package differs from the reviewed signed metadata');
  stage='actual-packaged-ui';run(join(win,'measure-packaged-ui.mjs'),[String(fixed.runs.windowsRelease),String(fixed.windowsArtifactID),'--complete-public']);const measured=await json(join(win,'packaged-ui-verification.json'));assert.equal(measured.dist.files,fixed.expectedFrontendFiles);assert.deepEqual(measured.dist.fileManifest.map(({path,bytes,sha256})=>({path,bytes,sha256})).sort((a,b)=>a.path.localeCompare(b.path)),fixed.expectedFrontend,'Actual packaged UI differs from the reviewed golden vector');report.frontendGoldenVectorSHA256=sha(JSON.stringify(fixed.expectedFrontend));report.frontendByteDifferences=0;
  for(const [from,to] of [['windows-public-verification.json','windows-public-verification.json'],['signed-update.json','signed-update.json'],['packaged-ui-verification.json','packaged-ui-verification.json'],[`candidate-${fixed.runs.windowsRelease}-${fixed.windowsArtifactID}/candidate-verification.json`,'candidate-verification.json'],[`candidate-${fixed.runs.windowsRelease}-${fixed.windowsArtifactID}/retrieval.json`,'candidate-retrieval.json'],['windows-candidate-preflight.json','windows-candidate-preflight.json']])await copyFile(join(win,from),join(output,to));report.extractorSHA256=sha(await readFile(matches[0]));report.frontendFiles=measured.dist.files;report.frontendComparison='Exact packaged 14-file golden vector passed; root independently compares the same actual manifest';report.scope='Independent hosted Windows static/public consumer; original installation proof checked, no new installation or runtime execution.';
 }else{
  stage='fresh-complete-formal-git-source';const linux=join(work,'linux'),{sourceTreeHash,gitObjectHash,verifyFullSource}=await import(pathToFileURL(join(linux,'verify-full-source.mjs')));
  const entries=git('ls-tree','-rz',fixed.productCommit).toString('utf8').split('\0').filter(Boolean).map(v=>{const i=v.indexOf('\t'),[mode,type,hash]=v.slice(0,i).split(' ');assert.equal(type,'blob');return{path:v.slice(i+1),mode,gitBlobSHA1:hash};});assert.equal(entries.length,fixed.trackedFiles);assert.equal(sourceTreeHash(entries),fixed.productTree);
  const snapshot=join(linux,'full-source-'+fixed.productCommit),files=[];await mkdir(join(snapshot,'files'),{recursive:true});for(const e of entries){const b=git('cat-file','blob',e.gitBlobSHA1);assert.equal(gitObjectHash('blob',b),e.gitBlobSHA1);const dest=join(snapshot,'files',e.path);await mkdir(dirname(dest),{recursive:true});await writeFile(dest,b,{flag:'wx'});files.push({...e,bytes:b.length,sha256:sha(b)});}const lock=files.find(f=>f.path==='package-lock.json');assert(lock);
  await writeFile(join(snapshot,'manifest.json'),JSON.stringify({schemaVersion:1,status:'complete-git-source-snapshot',preparedAt:new Date().toISOString(),commit:fixed.productCommit,tree:fixed.productTree,fileCount:files.length,packageLockSHA256:lock.sha256,reviewedCriticalFiles:fixed.criticalFiles.length,gatesAtPreparation:'passed',acceptanceExecuted:false,files},null,2)+'\n');const full=await verifyFullSource(source),bindings=[];await mkdir(join(linux,'public-source'));
  for(const [path,name] of [['scripts/download-record.ts','download-record.ts'],['scripts/linux-download-record.ts','linux-download-record.ts'],['server/engine-artifact.ts','engine-artifact.ts'],['shared/engine-source-linux.json','engine-source-linux.json'],['package-lock.json','source-package-lock.json'],['scripts/linux-build.ts','linux-build.ts'],['LICENSE','LICENSE'],['NOTICE','NOTICE'],['THIRD_PARTY_NOTICES.md','THIRD_PARTY_NOTICES.md'],['SECURITY.md','SECURITY.md']]){const b=git('show',fixed.productCommit+':'+path);await writeFile(join(linux,'public-source',name),b,{flag:'wx'});bindings.push({source:fixed.productCommit+':'+path,destination:'public-source/'+name,bytes:b.length,sha256:sha(b)});}for(const r of frozen.files.filter(r=>r.path.startsWith('linux/')))bindings.push({source:'pinned consumer method',destination:r.path.slice(6),bytes:r.bytes,sha256:r.sha256});
  await writeFile(join(linux,'preparation.json'),JSON.stringify({status:'bound-to-passed-immutable-source',version:fixed.version,commit:fixed.productCommit,files:bindings,fullSource:{directory:full.directory,manifestSHA256:full.manifestSHA256,commit:full.commit,tree:full.tree,fileCount:full.files.length,packageLockSHA256:full.packageLockSHA256}},null,2)+'\n');await writeFile(join(linux,'release-source.json'),JSON.stringify(source)+'\n');
  stage='pinned-official-node-comparison-archive';const tools='/var/tmp/rivloom-linux-20260918/tools';await mkdir(tools,{recursive:true});const build=git('show',fixed.productCommit+':scripts/linux-build.ts').toString(),nodeSHA=/x64: \{ nodeSha256: '([a-f0-9]{64})', machine: 62 \}/.exec(build)?.[1];assert.match(nodeSHA||'',/^[a-f0-9]{64}$/);const name='node-v24.19.0-linux-x64',b=await get('https://nodejs.org/dist/v24.19.0/'+name+'.tar.xz',64*1024**2);assert.equal(sha(b),nodeSHA);await writeFile(join(tools,name+'.tar.xz'),b,{flag:'wx'});execFileSync('/usr/bin/tar',['-xJf',join(tools,name+'.tar.xz'),'-C',tools],{stdio:'pipe',timeout:60000});
  const officialNode=join(tools,name,'bin/node'),officialBinSHA256=sha(await readFile(officialNode)),setupNodeSHA256=sha(await readFile(process.execPath));assert.equal(setupNodeSHA256,officialBinSHA256,'setup-node executable differs from the locked official archive bin');verifiedReaderNode=officialNode;report.readerNode={version:process.version,officialArchiveURL:'https://nodejs.org/dist/v24.19.0/'+name+'.tar.xz',officialArchiveSHA256:nodeSHA,officialBinSHA256,setupNodeSHA256,byteMatch:true,nativeHarnessUsesVerifiedBinary:true};
  stage='live-linux-release-gate-before-package-execution';run(join(linux,'verify-public.mjs'),['gate',String(fixed.runs.linuxRelease)]);const linuxGate=await json(join(linux,'linux-public-gate.json'));assert.deepEqual({bytes:linuxGate.record.platforms['linux-x64'].bytes,sha256:linuxGate.record.platforms['linux-x64'].sha256},fixed.expectedLinuxPackage,'Linux release gate differs from the reviewed public package');
  stage='independent-public-curl-wget-and-native-lifecycle';run(join(linux,'public-wsl-check.mjs'),['downloads']);const dirs=(await readdir(linux,{withFileTypes:true})).filter(e=>e.isDirectory()&&/^public-wsl-[A-Za-z0-9]+$/.test(e.name));assert.equal(dirs.length,1);const proof=dirs[0].name+'/report.json';stage='actual-native-and-release-reader';run(join(linux,'verify-public.mjs'),['runtime',String(fixed.runs.linuxRelease),proof]);const verification=await json(join(linux,'linux-public-verification.json')),native=await json(join(linux,proof));assert.deepEqual({bytes:verification.bytes,sha256:verification.sha256},fixed.expectedLinuxPackage);assert.equal(native.status,'download-runtime-passed-awaiting-website');assert.equal(native.checks['wget-download'].tries,1);assert.equal(native.checks['wget-download'].automaticRetries,0);assert.equal(native.checks['wget-download'].partialResumed,false);assert(native.checks['wget-download'].actualCommandSha256!==native.checks['wget-download'].commandSha256);
  await copyFile(join(linux,proof),join(output,'linux-runtime-verification.json'));await copyFile(join(linux,'linux-public-verification.json'),join(output,'linux-public-verification.json'));
  stage='actual-owned-native-sandbox-cleanup';for(const mode of ['inspect','preflight','delete'])execFileSync('sudo',['-n',officialNode,join(linux,'linux-owned-cleanup.mjs'),mode,proof],{cwd:product,timeout:360000,maxBuffer:16*1024**2,stdio:['ignore','pipe','pipe']});const cleanup=await json(join(linux,'linux-cleanup.json'));assert.equal(cleanup.status,'completed');assert.equal(cleanup.sourceCommit,fixed.productCommit);assert.equal(cleanup.target,native.sandbox);assert.equal(cleanup.processCheck.complete,true);assert.deepEqual(cleanup.processCheck.active,[]);assert.equal(cleanup.boundary.linksFollowed,false);assert.equal(cleanup.oldSandboxesTouched,false);assert.equal(cleanup.userInstallationChanged,false);assert.deepEqual({bytes:cleanup.retained.bytes,sha256:cleanup.retained.sha256},fixed.expectedLinuxPackage);await copyFile(join(linux,'linux-cleanup.json'),join(output,'linux-cleanup.json'));
  const retained=join(linux,dirs[0].name,native.release.artifact.fileName),info=await lstat(retained);assert(info.isFile()&&!info.isSymbolicLink()&&info.nlink===1);assert.equal(info.uid,process.getuid());assert.equal(info.size,fixed.expectedLinuxPackage.bytes);assert.equal(sha(await readFile(retained)),fixed.expectedLinuxPackage.sha256);const after=await lstat(retained);for(const key of ['dev','ino','size','mtimeMs'])assert.equal(after[key],info[key]);await unlink(retained);await assert.rejects(lstat(retained),{code:'ENOENT'});report.hostedRetainedArchive={...fixed.expectedLinuxPackage,removedAfterFullVerification:true,smallHashProofPreserved:true};report.nativeSandboxCleanup=cleanup;report.actualConsumerUID=process.getuid();report.freshSourceManifestSHA256=full.manifestSHA256;report.completeGitSource={files:full.files.length,tree:full.tree,allLeafBytesHashVerified:true};report.websiteCommandVerification='pending actual website deployment; not claimed passed';report.scope='Independent GitHub-hosted Ubuntu native consumer; local WSL transport failures remain recorded separately; website command comparison follows actual deployment.';
 }
 stage='source-stability';assert.equal(git('status','--porcelain').toString().trim(),'');assert.equal(git('rev-parse','HEAD').toString().trim(),fixed.productCommit);for(const r of frozen.files)assert.equal(sha(await readFile(join(base,r.path))),r.sha256);report.status='passed';report.finishedAt=new Date().toISOString();
}catch(error){report.status='failed';report.failedStage=stage;Object.assign(report,diagnostics(error));report.finishedAt=new Date().toISOString();process.exitCode=1;}
await writeFile(join(output,'consumer-result.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,platform,failedStage:report.failedStage,productCommit:fixed.productCommit,consumerCommit:report.consumerCommit,producerBuildExecuted:false,publicationExecuted:false,storageMutations:0}));
