// Export application icons from the supplied artwork without redrawing the logo.
import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const artwork = join(root, 'src/assets/brand/rivloom-symbol-gradient.png');
const bytes = readFileSync(artwork);
const output = join(root, 'src-tauri/icons');
const generated = join(root, '.data/brand/build');
mkdirSync(generated, { recursive: true });
const svg = join(generated, 'rivloom-app-icon.svg');
// The nested viewBox removes only the original transparent margins. The light
// rounded backing keeps the supplied dark-blue mark readable on either taskbar.
writeFileSync(
  svg,
  `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <rect x="24" y="24" width="976" height="976" rx="208" fill="#f6f9ff"/>
  <svg x="206" y="127" width="612" height="770" viewBox="325 211 675 851">
    <image width="1254" height="1254" href="data:image/png;base64,${bytes.toString('base64')}"/>
  </svg>
</svg>\n`,
);
const result = spawnSync(
  process.execPath,
  [join(root, 'node_modules/@tauri-apps/cli/tauri.js'), 'icon', svg, '--output', output],
  { cwd: root, stdio: 'inherit', windowsHide: true },
);
if (result.error) throw result.error;
if (result.status !== 0) process.exit(result.status || 1);
copyFileSync(join(output, '32x32.png'), join(root, 'src/assets/brand/rivloom-favicon.png'));
// Give shell shortcuts a new resource path whenever the artwork changes, so an
// upgrade does not depend on Windows invalidating an icon cached for Rivloom.exe.
const iconHash = createHash('sha256').update(readFileSync(join(output, 'icon.ico'))).digest('hex');
const shellIcon = `brand/rivloom-${iconHash.slice(0, 12)}.ico`;
const configPath = join(root, 'src-tauri/tauri.conf.json');
const config = JSON.parse(readFileSync(configPath, 'utf8'));
config.bundle.resources['icons/icon.ico'] = shellIcon;
writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
writeFileSync(
  join(root, 'src-tauri/brand-icon.nsh'),
  `; Generated by scripts/brand-icons.mjs from the bundled ICO content.\n!define RIVLOOM_SHELL_ICON_RELATIVE "${shellIcon.replaceAll('/', '\\')}"\n`,
);
writeFileSync(
  join(generated, 'provenance.json'),
  JSON.stringify(
    {
      artwork: 'src/assets/brand/rivloom-symbol-gradient.png',
      sha256: createHash('sha256').update(bytes).digest('hex'),
      geometry: 'Original symbol, proportionally fitted within a light rounded square',
      exporter: '@tauri-apps/cli',
      generatedAt: new Date().toISOString(),
    },
    null,
    2,
  ) + '\n',
);
console.log('Exported Rivloom icons and favicon from the unchanged supplied symbol.');
